name: Generate Reports

on:
  workflow_dispatch:
    inputs:
      main_pokemon:
        description: 'Main Pokémon to filter decks'
        required: false
        default: ''
      secondary_pokemon:
        description: 'Secondary Pokémon to filter decks'
        required: false
        default: ''
      min_rank:
        description: 'Minimum rank to filter decks'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate report
      run: |
        python analyze.py --main_pokemon "${{ github.event.inputs.main_pokemon }}" --secondary_pokemon "${{ github.event.inputs.secondary_pokemon }}" --min_rank "${{ github.event.inputs.min_rank }}"

    - name: Update README with report links
      run: |
        echo "# Pokémon TCG Deck Analysis" > README.md
        echo "" >> README.md
        echo "This project analyzes Pokémon TCG decks and generates a report on card distributions and deck information." >> README.md
        echo "" >> README.md
        echo "## Available Reports" >> README.md
        for file in reports/*.md; do
          echo "- [$(basename $file)]($file)" >> README.md
        done

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git add reports/*.md
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Add or update markdown file"
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
