name: Scrape and Generate Reports

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */3 * * *" # Runs every 3 hours

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  run-scrape-and-generate-reports:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scrape.py
      run: python src/scrape.py

    - name: Generate reports from CSV
      run: python src/analyze.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A src/data/
        git add -A docs/
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Add or update markdown files and README"
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
