name: Scrape and Generate Reports

on:
  workflow_dispatch:
    inputs:
      end_tournament_id:
        description: 'End Tournament ID'
        required: true
      start_clusters:
        description: 'Start Clusters'
        required: true
        default: '300'
      end_clusters:
        description: 'End Clusters'
        required: true
        default: '600'

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  run-scrape-and-generate-reports:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scrape.py
      run: python scrape.py ${{ github.event.inputs.end_tournament_id }}

    - name: Run cluster.py
      run: python cluster.py ${{ github.event.inputs.start_clusters }} ${{ github.event.inputs.end_clusters }}

    - name: Generate reports from CSV
      run: python analyze.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add tournament_decks.csv progress.txt
        git add clustered_tournament_decks.csv silhouette_wcss.png
        git add README.md
        git add -A reports/
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Add or update markdown files and README"
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
