name: Scrape and Generate Reports

on:
  workflow_dispatch:
    inputs:
      end_tournament_id:
        description: 'End Tournament ID'
        required: true

permissions:
  contents: write

jobs:
  run-scrape-and-generate-reports:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scrape.py
      run: python scrape.py ${{ github.event.inputs.end_tournament_id }}

    - name: Generate reports from CSV
      run: |
        while IFS=',' read -r main_pokemon secondary_pokemon min_rank; do
          if [[ "$main_pokemon" != "mainpokemon" ]]; then
            python analyze.py --main_pokemon "$main_pokemon" --secondary_pokemon "$secondary_pokemon" --min_rank "$min_rank"
          fi
        done < reportrequirements.csv

    - name: Update README with report links
      run: |
        echo "# Pokémon TCG Deck Analysis" > README.md
        echo "" >> README.md
        echo "This project analyzes Pokémon TCG decks and generates a report on card distributions and deck information." >> README.md
        echo "" >> README.md
        echo "## Available Reports" >> README.md
        for file in reports/*.md; do
          echo "- [$(basename $file)]($file)" >> README.md
        done

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add tournament_decks.csv progress.txt
        git add README.md
        git add reports/*.md
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Add or update markdown files and README"
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
